# Turn on/off various plotted quantities (True=on; False=off)

# detection limits for current and future instruments
NIRCAM: True
NIRCAM_pred: False
NICMOS: True
STIS:   True
ACS :   True
generic ground-based: True # just show one ground-based curve? Overrides others.
SPHERE: True
GPI:    True
MagAO:  False
ELT :   False
GRAVITY: True
HABEX : False

# planets
DI_H:       True # known H-band contrasts of directly imaged planets
DI_B1_pred: False # predicted Band 1 from self-luminous, directly imaged planets
DI_B3_pred: True # predicted Band 3 from self-luminous, directly imaged planets
RV_pred:    'IMD' # [None, IMD, simple] predicted reflected light from known RV planets from either a simple Lambertian or the Imaging Mission Database
solar_system: True # Earth & Jupiter
Tau_Ceti:    False # Tau Ceti e & f data points
Tau_Ceti_axis: False # Tau Ceti e top y axis & label
Prox_Cen:   False # Proxima Centauri b

# CGI performance requirement and predictions (linestyle below)
req:       False # CGI L1 requirement  
cons_mode:    False # False (default): optimistic performance. True: conservative performance
# The same performance level (either optimistic or conservative) is used in all the following modes:
pred_img_short:   True # prediction for imaging with short exposure times
pred_img_medium:  True # prediction for imaging with intermediate exposure times
pred_img_long:   True # prediction for imaging with long exposure times
pred_spec_short:   True # prediction for spectroscopy detection limit with short exposure times
pred_spec_medium:  True # prediction for spectroscopy detection limit with intermediate exposure times
pred_spec_long:    True # prediction for spectroscopy detection limit with long exposure times
pred_wide_img_short:  True # prediction for extended source detection limit with short exposure times
pred_wide_img_medium: True # prediction for extended source detection limit with intermediate exposure times
pred_wide_img_long:   True # prediction for extended source detection limit with long exposure times
exp_t:      True # print exposures times used for predictions?

# old requirements (kept only for references)
old_L2req_img:    False # old L2 imaging requirement. Not longer exists.
old_L2req_spec:   False # old L2 spectroscopy requirement. No longer exists.
old_L2req_wide_img: False # old L2 extended source imaging requirement. No longer exists.

# plotting parameters
fig_width:  6.5 # inches
fig_height: 5.5 # inches
save_pdf:   False # output PDF?
save_jpg:   False # output JPG?
jpg_dpi:    200
save_png:   True # output PNG?
png_dpi:    300


color_by_lambda:  'simple'  # [ full / simple / minimal / none ] color code by  bandpass
timestamp:    True  # print date on plot

math_font:   'stixsans' # 'stix' (times), 'stixsans' (sans-serif), 'cm' (default latex)
plot_font_size:  13  # font size for axis labels / title, etc.
legend_font_size: 7.5  # font size for legend text
label_font_size:  9  # font size for detection limit curve labels

roman_linewidth: 2.5 # line width for Roman BTRs and detection limit curves
other_linewidth:  1 # line width for other instruments' detection limit curves

roman_linestyle_short: '-.' # line style for Roman detection curves with short integration times
roman_linestyle_medium: '--' # line style for Roman detection curves with intermediate integration times
roman_linestyle_long: '-' # line style for Roman detection curves with long integration times

rv_markersize:      50 # reflected light RV marker size
di_markersize:      40 # self-luminous planets marker size
marker_edge_width:  0.5  # width of borders on scatter plot markers

# plot x and y limits
x0: 0.03
x1: 5
y0: 3E-11
y1: 3E-3
