# Turn on/off various plotted quantities (True=on; False=off)
ELT :   False
HABEX : False
NIRCAM: True
NICMOS: True
STIS:   True
ACS :   True
SPHERE: True
GPI:    True

DI_H:       True # known H-band contrasts of directly imaged planets
DI_B1_pred: True # predicted Band 1 from self-luminous, directly imaged planets
DI_B3_pred: True # predicted Band 3 from self-luminous, directly imaged planets
RV_pred:    True # predicted reflected light from Jovian planets
solar_system: True # Earth & Jupiter
Tau_Ceti:    False # Tau Ceti e & f
Prox_Cen:   False # Proxima Centauri b

BTR_img:    False # imaging BTR
BTR_spec:   False # spectroscopy BTR
BTR_disk:   False # extended surface brightness BTR, translated to contrast in 1FWHM aperture

# plotting parameters
fig_width:  6 # inches
fig_height: 5 # inches
save_pdf:   True # output PDF?
save_jpg:   False # output JPG?
jpg_dpi:    200

color_by_lambda:  'simple'  # [ full / simple / none ] color code by  bandpass
is_draft:    True  # print DRAFT & date on plot

math_font:   'stixsans' # 'stix' (times), 'stixsans' (sans-serif), 'cm' (default latex)
plot_font_size:  12  # font size for axis labels / title, etc.
legend_font_size: 7  # font size for legend text
label_font_size:  8  # font size for detection limit curve labels

wfirst_linewidth: 4 # line width for WFIRST BTRs and detection limit curves
other_linewidth:  1 # line width for other instruments' detection limit curves

rv_markersize:      35 # reflected light RV marker size
di_markersize:      30 # self-luminous planets marker size
marker_edge_width:  0.5  # width of borders on scatter plot markers

# plot x and y limits
x0: 0.07
x1: 5
y0: 1E-11
y1: 1E-3
